# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geoloc-mysql"
  config.vm.network :public_network, ip: "192.168.11.58"
  config.vm.network "public_network", :bridge => 'p4p1'
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 2048
  end
end
