- hosts: vagrant
  sudo: true
  user: vagrant
  tasks:
    - name: check apt last update
      stat: path=/var/cache/apt
      register: apt_cache_stat
    - name: update apt if needed
      apt: update_cache=yes
      when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12

    - apt: pkg=mysql-client update_cache=no state=latest
    - apt: pkg=libmysqlclient-dev update_cache=no state=latest
    - apt: pkg=python-dev update_cache=no state=latest
    - apt: pkg=python-pip update_cache=no state=latest
    - apt: pkg=pkg-config update_cache=no state=latest
    - apt: pkg=zip update_cache=no state=latest
    - apt: pkg=unzip update_cache=no state=latest
    - apt: pkg=vim update_cache=no state=latest
    - apt: pkg=libaio1 update_cache=no state=latest
    - pip: name=MySQL-python

    - command: mkdir -p /tmp/mysql
    - get_url: url="http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.17-debian6.0-x86_64.deb" dest=/tmp/mysql/mysql-5.6.17-debian6.0-x86_64.deb
    - command: chdir=/tmp/mysql sudo dpkg -i mysql-5.6.17-debian6.0-x86_64.deb
    - user: name=mysql group=mysql home=/home/mysql shell=/bin/bash state=present

    - copy: src=./conf/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644
    - command: sudo chown -R mysql:mysql /opt/mysql/server-5.6
    - command: sudo install -o mysql -g mysql -d /data/mysql
    - command: sudo /opt/mysql/server-5.6/scripts/mysql_install_db --user=mysql --datadir=/data/mysql --no-default

    - command: sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysqld
    - command: sudo update-rc.d mysqld defaults

    - name: copy .my.cnf file with root password credentials
      template: src=./conf/.my.cnf dest=/root/.my.cnf owner=root mode=0600

    - name: be sure mysqld is running and enabled
      service: name=mysqld state=running enabled=yes

    - name: delete anonymous MySQL server user
      action: mysql_user user="" state="absent"

    - name: remove the MySQL test database
      action: mysql_db db=test state=absent

    - name: Create database
      mysql_db: db=geoloc state=present encoding=utf8

    - name: Create database user
      mysql_user: >
        name=geoloc
        password=geoloc
        host=%
        priv=geoloc.*:ALL
        state=present
