# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geoloc-mysql"
  config.vm.network :private_network, ip: "192.168.33.59"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision_vagrant.yml"  # playbook file
    ansible.inventory_path = "hosts"  # inventory file
  end
end
